<?xml version="1.0" encoding="UTF-8"?>
<robot rpa="false" generated="20220405 11:33:07.968" schemaversion="2" generator="Robot 4.1.3 (Python 2.7.17 on linux2)">
<suite source="/home/stsch0219/PycharmProjects/Automation-Testing-With-Robot-Framew/Tests/Others/DDT_Excel.robot" id="s1" name="DDT Excel">
<kw type="SETUP" name="Start testcase" library="common">
<kw name="open browser">
<arg>${url}</arg>
<arg>${browser}</arg>
<msg timestamp="20220405 11:33:08.004" level="FAIL">No keyword with name 'open browser' found.</msg>
<status status="FAIL" endtime="20220405 11:33:08.004" starttime="20220405 11:33:08.004"/>
</kw>
<kw name="maximize browser window">
<status status="NOT RUN" endtime="20220405 11:33:08.007" starttime="20220405 11:33:08.006"/>
</kw>
<kw name="Sleep" library="BuiltIn">
<arg>2s</arg>
<doc>Pauses the test executed for the given time.</doc>
<status status="NOT RUN" endtime="20220405 11:33:08.007" starttime="20220405 11:33:08.007"/>
</kw>
<status status="FAIL" endtime="20220405 11:33:08.007" starttime="20220405 11:33:08.000"/>
</kw>
<test id="s1-t1" name="Verify login with invalid scenarios">
<status status="FAIL" endtime="20220405 11:33:08.008" starttime="20220405 11:33:08.007">Parent suite setup failed:
No keyword with name 'open browser' found.</status>
</test>
<kw type="TEARDOWN" name="Finish testcase" library="common">
<kw name="close browser">
<msg timestamp="20220405 11:33:08.011" level="FAIL">No keyword with name 'close browser' found.</msg>
<status status="FAIL" endtime="20220405 11:33:08.011" starttime="20220405 11:33:08.011"/>
</kw>
<status status="FAIL" endtime="20220405 11:33:08.012" starttime="20220405 11:33:08.009">No keyword with name 'close browser' found.</status>
</kw>
<doc>DDT approach using builtin keywords</doc>
<status status="FAIL" endtime="20220405 11:33:08.012" starttime="20220405 11:33:07.970">Suite setup failed:
No keyword with name 'open browser' found.

Also suite teardown failed:
No keyword with name 'close browser' found.</status>
</suite>
<statistics>
<total>
<stat fail="1" skip="0" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" skip="0" id="s1" name="DDT Excel" pass="0">DDT Excel</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220405 11:33:07.992" level="ERROR">Error in file '/home/stsch0219/PycharmProjects/Automation-Testing-With-Robot-Framew/Tests/Others/DDT_Excel.robot' on line 3: Importing library 'SeleniumLibrary' failed: ImportError: No module named SeleniumLibrary
Traceback (most recent call last):
  None
PYTHONPATH:
  /home/stsch0219/.local/bin
  /usr/lib/python2.7
  /usr/lib/python2.7/plat-x86_64-linux-gnu
  /usr/lib/python2.7/lib-tk
  /usr/lib/python2.7/lib-old
  /usr/lib/python2.7/lib-dynload
  /home/stsch0219/.local/lib/python2.7/site-packages
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages</msg>
<msg timestamp="20220405 11:33:07.995" level="ERROR">Error in file '/home/stsch0219/PycharmProjects/Automation-Testing-With-Robot-Framew/Resources/DDT/common.robot' on line 3: Importing library 'SeleniumLibrary' failed: ImportError: No module named SeleniumLibrary
Traceback (most recent call last):
  None
PYTHONPATH:
  /home/stsch0219/.local/bin
  /usr/lib/python2.7
  /usr/lib/python2.7/plat-x86_64-linux-gnu
  /usr/lib/python2.7/lib-tk
  /usr/lib/python2.7/lib-old
  /usr/lib/python2.7/lib-dynload
  /home/stsch0219/.local/lib/python2.7/site-packages
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages</msg>
<msg timestamp="20220405 11:33:07.998" level="ERROR">Error in file '/home/stsch0219/PycharmProjects/Automation-Testing-With-Robot-Framew/Tests/Others/DDT_Excel.robot' on line 5: Importing library 'DataDriver' failed: ImportError: No module named DataDriver
Traceback (most recent call last):
  None
PYTHONPATH:
  /home/stsch0219/.local/bin
  /usr/lib/python2.7
  /usr/lib/python2.7/plat-x86_64-linux-gnu
  /usr/lib/python2.7/lib-tk
  /usr/lib/python2.7/lib-old
  /usr/lib/python2.7/lib-dynload
  /home/stsch0219/.local/lib/python2.7/site-packages
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages</msg>
</errors>
</robot>
